
def flux():
    # Install flux but without the repo syncing
    k8s_yaml('stacks/flux-system/gotk-components.yaml')

    k8s_resource(
        workload='source-controller',
        objects=['{}.source.toolkit.fluxcd.io:customresourcedefinition'.format(kind) for kind in ['buckets', 'gitrepositories', 'helmrepositories', 'helmcharts', 'ocirepositories']],
        labels=['flux']
    )

    k8s_resource(
        workload='kustomize-controller',
        objects=['kustomizations.kustomize.toolkit.fluxcd.io:customresourcedefinition'],
        labels=['flux']
    )

    k8s_resource(
        workload='helm-controller',
        objects=['helmreleases.helm.toolkit.fluxcd.io:customresourcedefinition'],
        labels=['flux']
    )

    k8s_resource(
        workload='notification-controller',
        objects=['{}.notification.toolkit.fluxcd.io:customresourcedefinition'.format(kind) for kind in ['alerts', 'providers', 'receivers']],
        labels=['flux']
    )
