# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

[settings]
experimental = true
all_compile = false

[tools]
# Build tools
"github:cue-lang/cue" = "0.16.1"
helm = "4.1.4"
kustomize = "5.8.1"
kubeconform = "0.7.0"
# Developer tools
kubectl = "1.36.0"
kind = "0.31.0"
tilt = "0.37.3"
prek = "0.3.13"
flux2 = "2.8.6"
"github:cozystack/talm" = "0.26.1"

[tasks]
build.run = [
  "cue cmd render ./... -t env=dev",
  "cue cmd render ./... -t env=prod",
]

test.run = [
  "kind create cluster --config kind.yaml",
  "tilt ci --context kind-autolab",
  "kubectl wait -A --all --for=condition=ready --timeout=5m kustomization",
  "kubectl wait -A --all --for=condition=ready --timeout=5m helmrelease ",
  "kind delete cluster --name autolab",
]

renovate.run = '''
  docker run --rm \
    --volume .:/usr/src/app \
    --user $UID:$GID \
    -e LOG_LEVEL=debug \
    -e RENOVATE_GITHUB_COM_TOKEN=$(gh auth token) \
    docker.io/renovate/renovate:latest \
      --platform=local
'''
