# Copyright © 2025 Colden Cullen
# SPDX-License-Identifier: MIT

[settings]
experimental = true
all_compile = false

[plugins]
krew = "https://github.com/soupglasses/mise-krew"

[tools]
# Build tools
sops = "3.13.1"
helmfile = "1.5.5"
helm = "4.2.2"
kustomize = "5.8.1"
kubectl = "1.36.2"
"github:postfinance/topf" = "0.4.1"
# Test Tools
kubeconform = "0.8.0"
kind = "0.32.0"
tilt = "0.37.4"
# Dev tools
prek = "0.4.5"
flux2 = "2.8.8"

# Helpful tools
"krew:ctx" = "v0.11.0"
"krew:ns" = "v0.11.0"
"krew:cert-manager" = "v2.1.0"
"krew:cnpg" = "v1.29.1"

[tasks]
build.run = ["helmfile template -e production > rendered.yaml"]

"lint:helmfile".run = "helmfile lint"
"lint:kubeconform".run = "helmfile template | kubeconform -skip CustomResourceDefinition -schema-location default  -schema-location {{ 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' }}"
"lint".depends = "lint:*"

renovate.run = '''
  docker run --rm \
    --volume .:/usr/src/app \
    --user $UID:$GID \
    -e LOG_LEVEL=debug \
    -e RENOVATE_GITHUB_COM_TOKEN=$(gh auth token) \
    docker.io/renovate/renovate:latest \
      --platform=local
'''

# Testing commands
"test:kind:setup".run = "kind create cluster --config kind.yaml"
"test:kind:teardown".run = "kind delete cluster --name autolab"

[tasks."test:run"]
run = [
  "tilt ci",
  "helmfile test"
]

[tasks.test]
usage = '''
arg "<cluster-type>"  {
  help "The type of local cluster to run for testing"
  choices "kind"
  default "kind"
}
'''
run = [
  { task = "test:{{ usage.cluster_type }}:setup" },
  { task = "test:run" },
  { task = "test:{{ usage.cluster_type }}:teardown" },
]
