---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
registry: ctlptl-registry
product: kind
name: kind-autolab
kindV1Alpha4Cluster:
  nodes:
    - role: control-plane
    - role: worker
    - role: worker
