# Helmfile configuration
# Documentation: https://helmfile.readthedocs.io/

# Environment-specific values
# Usage: helmfile -e <environment> apply
environments:
  default:
    values:
      - externalUrl: "localhost"
        certIssuer: "self-signed"
  production:
    values:
      - externalUrl: dislogi.net
        certIssuer: acme-prod

---
# Common Helm defaults applied to all releases
helmDefaults:
  createNamespace: true
  wait: true
  timeout: 300

apiVersions:
  - monitoring.coreos.com/v1

# Helm chart repositories
repositories:
  - name: prometheus-community
    url: ghcr.io/prometheus-community/charts
    oci: true
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server
  - name: cert-manager
    url: quay.io/jetstack/charts
    oci: true
  - name: cloudnative-pg
    url: ghcr.io/cloudnative-pg/charts
    oci: true
  - name: traefik
    url: https://traefik.github.io/charts
  - name: headlamp
    url: https://kubernetes-sigs.github.io/headlamp
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: rook-ceph
    url: https://charts.rook.io/release

# Helm releases
releases:
  - name: prereqs
    createNamespace: false
    chart: ./charts/prereqs

  - name: gotk-components
    namespace: flux-system
    chart: ./flux-system

  - name: kube-prometheus-stack
    namespace: monitoring
    timeout: 600
    chart: prometheus-community/kube-prometheus-stack

  - name: metrics-server
    namespace: monitoring
    chart: metrics-server/metrics-server
    version: 3.13.0
    needs:
      - monitoring/kube-prometheus-stack
    values:
      - args:
          - --kubelet-insecure-tls
        metrics:
          enabled: true
        serviceMonitor:
          enabled: true

  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    version: v1.20.2
    needs:
      - monitoring/kube-prometheus-stack
    values:
      - crds:
          enabled: true
        config:
          featureGates:
            ServerSideApply: true
        prometheus:
          servicemonitor:
            enabled: true

  - name: cnpg
    namespace: cnpg-system
    chart: cloudnative-pg/cloudnative-pg
    version: 0.28.2
    needs:
      - monitoring/kube-prometheus-stack
    values:
      - cluster:
          instances: 2
          monitoring:
            enabled: true

  - name: cnpg-plugin-barman-cloud
    namespace: cnpg-system
    chart: cloudnative-pg/plugin-barman-cloud
    version: 0.6.0
    needs:
      - cnpg-system/cnpg
      - cert-manager/cert-manager

  - name: database
    namespace: cnpg-system
    chart: ./charts/database
    needs:
      - cnpg-system/cnpg
      - cnpg-system/cnpg-plugin-barman-cloud

  - name: traefik
    namespace: gateway
    chart: traefik/traefik
    version: 40.2.0
    needs:
      - /prereqs
      - monitoring/kube-prometheus-stack
    values:
      - providers:
          kubernetesIngress:
            enabled: false
          kubernetesCRD:
            enabled: false
          kubernetesGateway:
            enabled: true
            statusAddress:
              service:
                enabled: true
        service:
          annotations:
            metallb.io/loadBalancerIPs: 10.0.1.3
            tilt.dev/port-forward: "8080:80"
        ports:
          web:
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
          websecure:
            asDefault: true
        gateway:
          listeners:
            web:
              namespacePolicy:
                from: All
            websecure:
              port: 8443
              protocol: HTTPS
              namespacePolicy:
                from: All
              certificateRefs:
                - name: cert-tls-gateway
        metrics:
          prometheus:
            serviceMonitor:
              enabled: true

  - name: gateway
    namespace: gateway
    chart: ./charts/gateway
    needs:
      - gateway/traefik
      - cert-manager/cert-manager

  - name: headlamp
    namespace: headlamp
    chart: headlamp/headlamp
    version: 0.42.0
    values:
      - config:
          watchPlugins: true
          extraArgs:
            - -otlp-endpoint=''
        pluginsManager:
          enabled: true
          configContent: |
            installOptions:
              parallel: true
              maxConcurrent: 2
            plugins:
              - name: flux
                source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
                version: 0.6.0
              - name: cert-manager
                source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
                version: 0.1.0
              - name: kompose
                source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_kompose
                version: 0.1.1-beta-1

  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: v0.15.3
    createNamespace: false
    needs:
      - /prereqs
      - monitoring/kube-prometheus-stack
    values:
      - crds:
          enabled: true
        prometheus:
          serviceAccount: prometheus-kube-prometheus-prometheus
          namespace: metallb-system
          serviceMonitor:
            enabled: true

  - name: load-balancer
    namespace: metallb-system
    chart: ./charts/load-balancer
    needs:
      - metallb-system/metallb

  - name: rook-ceph-operator
    namespace: rook-ceph
    chart: rook-ceph/rook-ceph
    version: v1.19.5
    needs:
      - monitoring/kube-prometheus-stack
    values:
      - monitoring:
          enabled: true
        serviceMonitor:
          enabled: true
