apiVersion: v1
kind: Secret
metadata:
    name: b2-token
    namespace: cnpg-system
immutable: true
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:11jdLsTpRNhXKWONR/Z95gTV9wOFMAHfqQ==,iv:swLZm2xo8l0hFNrAh4OGHZurRUl5U9/w8NLn7yay+zQ=,tag:Mt+dtmPLOOKFNb3AEiSN1Q==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:i0rcAIJecXDcdo9mw8saJ6TfOlx+u8t4DA8BqFQMQQ==,iv:spZHxlmgqlANrAMqAlRM30eT/01MqoqWr2ORxv8iaNk=,tag:KVnPn5H6zUxc/5jLQRkRww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeDNDTG1KYWg3TjdwSVFF
            U1AwNm1zMS9lSVBhV0hVekNxc2l3SnlDdlY4CmNabEJDSmg0RFdQeVhSR3BEVjhF
            QWlBRjRYazgzRlp5VWt1dkZJSzMzemcKLS0tIGFTd3AwMHJ6ODRYdEowMFRza21F
            VHBUR05WTWE1djdjT09yMy95cC8zcE0KO8KkWZrUMSLcP2oMw/XLioOEHBwhg/eS
            I2nMf3WxW86FoNCh27E98A/5goJZa88POJTaTydGzdZKV/dW/jJZFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dnmjq02vg67ht272vy2ykntwg9ng4wnnwy3z0u7aeqg3k8538vjq00uadq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T18:46:25Z"
    mac: ENC[AES256_GCM,data:ve/XNBaFeyka0U7nlsTYIDOAzL8v9UhQiYwXgU/R5qdz1w5OgD9Wjf1pL5on31LE87gIdwohEqerjIQ8u5GE5LSbSpp58YbxOmwNsCrDEBfvDV3alN/CrXc38TAKfWNmR+A3A2Qp7pKQH1qb+EyZhwCer+NRPMPdlZZTlmng85k=,iv:8GgWvupqY0YWKMcCx9N6wGLudZkfju9YjCxY/qQglCg=,tag:1detvktgqPWPTLznMPtZeA==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    namespace: gateway
    name: cloudflare-api-token
immutable: true
stringData:
    account-id: ENC[AES256_GCM,data:20nYfDjMLPz13ibMH6NyTNYMbjRzNuUF73xaXwnVET8=,iv:uLhtMXCgqV2RXHmBkPDGfsk5n3P81O7afRx6RRP/yB8=,tag:bh0t5b1+vDLNS+3usI/rSA==,type:str]
    api-key: ENC[AES256_GCM,data:4Xa+LGxLpaVNvCZyiU8C2sQZCS6W5Qq6F3Z6DtuS9G9b/18VUHyv7qSHu98wmdKQNbGcJDQ=,iv:xRSodh4BQCCxjGNjRPC0h9jC5W+gr1T+K5FTeDEnaBM=,tag:DxRqkbova7s5GNfwMs5IHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeDNDTG1KYWg3TjdwSVFF
            U1AwNm1zMS9lSVBhV0hVekNxc2l3SnlDdlY4CmNabEJDSmg0RFdQeVhSR3BEVjhF
            QWlBRjRYazgzRlp5VWt1dkZJSzMzemcKLS0tIGFTd3AwMHJ6ODRYdEowMFRza21F
            VHBUR05WTWE1djdjT09yMy95cC8zcE0KO8KkWZrUMSLcP2oMw/XLioOEHBwhg/eS
            I2nMf3WxW86FoNCh27E98A/5goJZa88POJTaTydGzdZKV/dW/jJZFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dnmjq02vg67ht272vy2ykntwg9ng4wnnwy3z0u7aeqg3k8538vjq00uadq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T18:46:25Z"
    mac: ENC[AES256_GCM,data:ve/XNBaFeyka0U7nlsTYIDOAzL8v9UhQiYwXgU/R5qdz1w5OgD9Wjf1pL5on31LE87gIdwohEqerjIQ8u5GE5LSbSpp58YbxOmwNsCrDEBfvDV3alN/CrXc38TAKfWNmR+A3A2Qp7pKQH1qb+EyZhwCer+NRPMPdlZZTlmng85k=,iv:8GgWvupqY0YWKMcCx9N6wGLudZkfju9YjCxY/qQglCg=,tag:1detvktgqPWPTLznMPtZeA==,type:str]
    version: 3.13.1
