---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: b2-store
  namespace: cnpg-system
spec:
  configuration:
    destinationPath: b2://colden-ballard-prod-cnpg/
    endpointURL: https://s3.us-west-000.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: b2-token
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: b2-token
        key: ACCESS_SECRET_KEY
    wal:
      compression: bzip2
