{{- define "talm.discovered.system_disk_name" }}
{{- $systemDisk := (lookup "systemdisk" "" "system-disk") }}
{{- if $systemDisk }}
{{- $systemDisk.spec.devPath }}
{{- else }}
{{- $disk := "/dev/sda" }}
{{- range (lookup "disks" "" "").items }}
{{- if or .spec.wwid .spec.model }}
{{- $disk = .spec.dev_path }}
{{- break }}
{{- end }}
{{- end }}
{{- $disk }}
{{- end }}
{{- end }}

{{- define "talm.discovered.machinetype" }}
{{- (lookup "machinetype" "" "machine-type").spec }}
{{- end }}

{{- /*
  talm.discovered.hostname returns the live node's hostname when it looks
  user-set, and falls back to a synthetic talos-XXXXX placeholder otherwise.

  Boot-to-talos and Talos's own pre-config state can leave a node with a
  transient placeholder hostname — `rescue` (Hetzner rescue OS), `talos`
  (Talos default before any config), `localhost` and `localhost.localdomain`
  (kernel and initramfs defaults).
  Propagating those names into the rendered template would let
  `talm template -I` write them back into the node body, where they read
  as "applied state" to the user; the next apply replays the placeholder,
  discovery returns it, and the loop never resolves to the user's intended
  per-node hostname.

  Filtering well-known transient names and falling through to the
  address-derived placeholder gives the user a visibly synthetic
  `hostname: "talos-abcde"` in the autogenerated body, signalling
  "replace me with a real per-node value".

  The match is case-insensitive: Sprig's `has` is exact-match, but some
  PXE/DHCP servers hand out title-case forms (`Localhost`) or all-caps
  (`TALOS`, `RESCUE`), and the trap-loop is identical for those. Lower-
  casing $name before the comparison covers them with no behavior change
  for the canonical lowercase forms.
*/ -}}
{{- define "talm.discovered.hostname" }}
{{- $hostname := lookup "hostname" "" "hostname" }}
{{- $name := "" }}
{{- if $hostname }}
{{- $name = $hostname.spec.hostname }}
{{- end }}
{{- if and $name (not (has (lower $name) (list "rescue" "talos" "localhost" "localhost.localdomain"))) }}
{{- $name }}
{{- else }}
{{- printf "talos-%s" (include "talm.discovered.default_addresses_by_gateway" . | sha256sum | trunc 5) }}
{{- end }}
{{- end }}

{{- define "talm.discovered.disks_info" }}
# -- Discovered disks:
{{- range (lookup "disks" "" "").items }}
{{- if or .spec.wwid .spec.model }}
# {{ .spec.dev_path }}:
#    model: {{ .spec.model }}
#    serial: {{ .spec.serial }}
#    wwid: {{ .spec.wwid }}
#    size: {{ .spec.pretty_size }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.system_disk_nvme_id" }}
{{- $diskName := (include "talm.discovered.system_disk_name" .) }}
{{- $diskStablePath := "" }}
{{- range (lookup "disks" "" "").items }}
{{- if and (eq .spec.dev_path $diskName) (eq .spec.transport "nvme") .spec.wwid }}
{{- $diskStablePath = (printf "/dev/disk/by-id/nvme-%s" .spec.wwid) }}
{{- break }}
{{- end }}
{{- end }}
{{- if $diskStablePath }}
{{- $diskStablePath }}
{{- else }}
{{- $diskName }} # Unable to determine a stable NVMe disk path, falling back to the disk name
{{- end }}
{{- end }}

{{- define "talm.discovered.default_addresses" }}
{{- with (lookup "nodeaddress" "" "default") }}
{{- toJson .spec.addresses }}
{{- end }}
{{- end }}

{{- /* JSON list of IPv4 addresses on the link carrying the IPv4
       default route. Filters routes to family=inet4 because consumers
       (cozystack and generic chart helpers) pair the returned addresses
       with a hardcoded IPv4 destination route — selecting the first
       default route regardless of family on a dual-stack node would
       cascade into the IPv6 family being applied to the address filter,
       and the node's IPv4 addresses would silently disappear from the
       rendered config. Mirrors gateway_by_link's IPv4-only convention. */ -}}
{{- define "talm.discovered.default_addresses_by_gateway" }}
{{- $linkName := "" }}
{{- $family := "" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- $linkName = .spec.outLinkName }}
{{- $family = .spec.family }}
{{- break }}
{{- end }}
{{- end }}
{{- $addresses := list }}
{{- range (lookup "addresses" "" "").items }}
{{- if and (eq .spec.linkName $linkName) (eq .spec.family $family) (not (eq .spec.scope "host")) }}
{{- if not (hasPrefix (printf "%s/" $.Values.floatingIP) .spec.address) }}
{{- $addresses = append $addresses .spec.address }}
{{- end }}
{{- end }}
{{- end }}
{{- toJson $addresses }}
{{- end }}

{{- define "talm.discovered.physical_links_info" }}
# -- Discovered interfaces:
{{- range (lookup "links" "" "").items }}
{{- if and .spec.busPath (regexMatch "^(eno|eth|enp|enx|ens)" (.metadata.id | toString)) }}
# {{ .metadata.id }}:
#   hardwareAddr:{{ .spec.hardwareAddr }}
#   busPath: {{ .spec.busPath }}
#   driver: {{ .spec.driver }}
#   vendor: {{ .spec.vendor }}
#   product: {{ .spec.product }})
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_name" }}
{{- range (lookup "addresses" "" "").items }}
{{- if has .spec.address (fromJsonArray (include "talm.discovered.default_addresses" .)) }}
{{- .spec.linkName }}
{{- end }}
{{- end }}
{{- end }}

{{- /* All four default_link_*_by_gateway helpers below are IPv4-only.
       They identify the link that carries the chart's primary uplink, and
       that uplink is the same one default_gateway / default_addresses_by_gateway
       configure — selecting a different link here would produce a config
       where LinkConfig.name attaches to one NIC while LinkConfig.routes /
       addresses describe a different NIC, leaving both unconfigured.
       Picking the IPv4 default route's outLinkName keeps the whole
       chain pointed at the same NIC on multi-NIC dual-stack nodes
       (typical Hetzner shape: management NIC on IPv4, public NIC on
       IPv6, default routes on different links). Symmetric with
       gateway_by_link / default_gateway / default_addresses_by_gateway. */ -}}
{{- define "talm.discovered.default_link_name_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- .spec.outLinkName }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_address_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- (lookup "links" "" .spec.outLinkName).spec.hardwareAddr }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_bus_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- (lookup "links" "" .spec.outLinkName).spec.busPath }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_link_selector_by_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- with (lookup "links" "" .spec.outLinkName) }}
busPath: {{ .spec.busPath }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.predictable_link_name" -}}
{{ printf "enx%s" (lookup "links" "" . | dig "spec" "hardwareAddr" . | replace ":" "") }}
{{- end }}

{{- /* Scalar IPv4 default-route gateway (dst="", main table, family=inet4).
       Empty if the node has no IPv4 default route. IPv4-only by convention
       so the helper stays symmetric with gateway_by_link and so consumers
       that pair the returned gateway with an IPv4 destination
       (`network: 0.0.0.0/0` on the legacy schema, or no `network:` field
       on the typed RouteConfig schema) never end up with a malformed
       IPv4-dst + IPv6-gateway route on a dual-stack node. Talos derives
       the route family from the gateway literal at validation time, so a
       RouteConfig with gateway `fe80::1` and no `network:` field is
       rejected outright — silently breaking Layer2 VIP and any other
       feature that depends on the chart-emitted route entry. */ -}}
{{- define "talm.discovered.default_gateway" }}
{{- range (lookup "routes" "" "").items }}
{{- if and (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") }}
{{- .spec.gateway }}
{{- break }}
{{- end }}
{{- end }}
{{- end }}

{{- define "talm.discovered.default_resolvers" }}
{{- with (lookup "resolvers" "" "resolvers") }}
{{- toJson .spec.dnsServers }}
{{- end }}
{{- end }}

{{- define "talm.discovered.existing_interfaces_configuration" }}
{{- with (lookup "machineconfig" "" "v1alpha1") }}
{{- $spec := .spec }}
{{- $interfaces := list }}
{{- if kindIs "string" $spec }}
{{- $interfaces = $spec | fromYaml | dig "machine" "network" "interfaces" (list) }}
{{- else }}
{{- $interfaces = $spec | dig "machine" "network" "interfaces" (list) }}
{{- end }}
{{- if $interfaces }}
{{- $interfaces | toYaml }}
{{- end }}
{{- end }}
{{- end }}

{{- /* Get bond slave interfaces for a given bond index */ -}}
{{- define "talm.discovered.bond_slaves" -}}
{{- $bondIndex := . -}}
{{- $slaves := list -}}
{{- range (lookup "links" "" "").items -}}
{{- if and (eq .spec.slaveKind "bond") (eq (int .spec.masterIndex) (int $bondIndex)) -}}
{{- $slaves = append $slaves .metadata.id -}}
{{- end -}}
{{- end -}}
{{- toJson $slaves -}}
{{- end -}}

{{- /* Generate bond configuration from bondMaster spec */ -}}
{{- define "talm.discovered.bond_config" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "bond") -}}
{{- $bondMaster := $link.spec.bondMaster -}}
{{- $slaves := fromJsonArray (include "talm.discovered.bond_slaves" $link.spec.index) -}}
bond:
  interfaces:
    {{- range $slaves }}
    - {{ . }}
    {{- end }}
  mode: {{ $bondMaster.mode }}
  {{- if $bondMaster.xmitHashPolicy }}
  xmitHashPolicy: {{ $bondMaster.xmitHashPolicy }}
  {{- end }}
  {{- if $bondMaster.lacpRate }}
  lacpRate: {{ $bondMaster.lacpRate }}
  {{- end }}
  {{- if $bondMaster.miimon }}
  miimon: {{ $bondMaster.miimon }}
  {{- end }}
  {{- if $bondMaster.updelay }}
  updelay: {{ $bondMaster.updelay }}
  {{- end }}
  {{- if $bondMaster.downdelay }}
  downdelay: {{ $bondMaster.downdelay }}
  {{- end }}
{{- end -}}
{{- end -}}

{{- /* Check if a link is a bond interface */ -}}
{{- define "talm.discovered.is_bond" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "bond") -}}
true
{{- end -}}
{{- end -}}

{{- /* Check if a link is a vlan interface */ -}}
{{- define "talm.discovered.is_vlan" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "vlan") -}}
true
{{- end -}}
{{- end -}}

{{- /* Get parent link name by linkIndex */ -}}
{{- define "talm.discovered.parent_link_name" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link $link.spec.linkIndex -}}
{{- $parentIndex := $link.spec.linkIndex -}}
{{- range (lookup "links" "" "").items -}}
{{- if eq (int .spec.index) (int $parentIndex) -}}
{{- .metadata.id -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- /* Get vlan ID from link */ -}}
{{- define "talm.discovered.vlan_id" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link $link.spec.vlan -}}
{{- $link.spec.vlan.vlanID -}}
{{- end -}}
{{- end -}}

{{- /* Generate vlan configuration */ -}}
{{- define "talm.discovered.vlan_config" -}}
{{- $linkName := . -}}
{{- $link := lookup "links" "" $linkName -}}
{{- if and $link (eq $link.spec.kind "vlan") -}}
vlans:
  - vlanId: {{ $link.spec.vlan.vlanID }}
{{- end -}}
{{- end -}}

{{- /*
  Multi-NIC discovery helpers (#125).

  The `default_*_by_gateway` family above resolves only the link carrying the
  default route (primary). Templates targeting nodes with secondary NICs
  (storage links on a control-plane, second uplink, etc.) need to enumerate
  every physical link and read its addresses/routes/MAC by name. The helpers
  below are the by-name building blocks; existing default_*_by_gateway helpers
  remain wrappers that resolve the primary link and call into these.
*/ -}}

{{- /* JSON list of physical link names (raw NICs only — not bond/vlan masters).
       Renamed from `physical_links` to avoid collision with the older
       `physical_links_info` helper, which renders YAML comments.
       Bond slaves are NOT filtered by this helper — callers that need to
       skip slaves (e.g. the multi-doc renderer that already emits the
       master's BondConfig) must filter on spec.slaveKind themselves, or
       use configurable_link_names below which already filters them. */ -}}
{{- define "talm.discovered.physical_link_names" -}}
{{- $names := list -}}
{{- range (lookup "links" "" "").items -}}
{{- if and .spec.busPath (regexMatch "^(eno|eth|enp|enx|ens)" (.metadata.id | toString)) -}}
{{- $names = append $names .metadata.id -}}
{{- end -}}
{{- end -}}
{{- toJson $names -}}
{{- end -}}

{{- /* JSON list of every link a user template can configure: physical NICs
       plus bond / vlan / bridge top-level links. Bond slaves (physical NICs
       enrolled into a bond master) are excluded — emitting a standalone
       LinkConfig for a slave alongside the master's BondConfig produces
       conflicting declarations Talos will reject during controller
       convergence. The slave-membership fact comes from spec.slaveKind
       (set by the link controller when a physical NIC is attached to a
       bond / bridge / team), so filtering on it covers slaves regardless
       of whether the master is bond, bridge, or future kinds. */ -}}
{{- define "talm.discovered.configurable_link_names" -}}
{{- $names := list -}}
{{- range (lookup "links" "" "").items -}}
{{- $isPhysical := and .spec.busPath (regexMatch "^(eno|eth|enp|enx|ens)" (.metadata.id | toString)) -}}
{{- $isVirtual := has (.spec.kind | toString) (list "bond" "vlan" "bridge") -}}
{{- $isSlave := and .spec.slaveKind (ne (.spec.slaveKind | toString) "") -}}
{{- if and (or $isPhysical $isVirtual) (not $isSlave) -}}
{{- $names = append $names .metadata.id -}}
{{- end -}}
{{- end -}}
{{- toJson $names -}}
{{- end -}}

{{- /* JSON list of CIDR addresses configured on the given link, excluding
       kernel-managed scopes (host loopback, link-local, nowhere) and
       addresses with no scope set at all. Both IPv4 and IPv6 globally-
       scoped addresses are returned — chart consumers (cozystack /
       generic multi-doc renderer) emit them verbatim into LinkConfig /
       VLANConfig / BondConfig.addresses, dropping the operator-declared
       floatingIP via an inline filter to keep the leader's transient VIP
       out of the static config. Add a per-family helper if a future
       caller needs IPv4- or IPv6-only output rather than tightening this
       one. */ -}}
{{- define "talm.discovered.addresses_by_link" -}}
{{- $linkName := . -}}
{{- $addresses := list -}}
{{- range (lookup "addresses" "" "").items -}}
{{- $hasScope := and .spec.scope (ne (.spec.scope | toString) "") -}}
{{- $skip := has (.spec.scope | toString) (list "host" "link" "nowhere") -}}
{{- if and (eq .spec.linkName $linkName) $hasScope (not $skip) -}}
{{- $addresses = append $addresses .spec.address -}}
{{- end -}}
{{- end -}}
{{- toJson $addresses -}}
{{- end -}}

{{- /* Scalar IPv4 gateway for the default route (dst="", main table) on the
       given link. Empty if the link has no IPv4 default route. IPv4-only by
       convention to avoid family/address mismatch on dual-stack nodes — add
       a sibling helper for IPv6 if you need it. */ -}}
{{- define "talm.discovered.gateway_by_link" -}}
{{- $linkName := . -}}
{{- range (lookup "routes" "" "").items -}}
{{- if and (eq .spec.outLinkName $linkName) (eq .spec.dst "") (not (eq .spec.gateway "")) (eq .spec.table "main") (eq (.spec.family | toString) "inet4") -}}
{{- .spec.gateway -}}
{{- break -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- /* JSON list of non-default routes on the given link, across all
       routing tables (the `table` field is included so callers can
       filter — gateway_by_link narrows to table=main, this helper does
       not). Each entry is a flat map {dst, gateway, family, table,
       priority} so consumers can fromJsonArray + range + dig. Absent
       fields are emitted as empty strings; present fields including the
       integer 0 (e.g. priority: 0) round-trip through toString. */ -}}
{{- define "talm.discovered.routes_by_link" -}}
{{- $linkName := . -}}
{{- $routes := list -}}
{{- range (lookup "routes" "" "").items -}}
{{- if and (eq .spec.outLinkName $linkName) (not (eq .spec.dst "")) -}}
{{- $gateway := "" -}}
{{- if not (kindIs "invalid" .spec.gateway) -}}{{- $gateway = printf "%v" .spec.gateway -}}{{- end -}}
{{- $family := "" -}}
{{- if not (kindIs "invalid" .spec.family) -}}{{- $family = printf "%v" .spec.family -}}{{- end -}}
{{- $table := "" -}}
{{- if not (kindIs "invalid" .spec.table) -}}{{- $table = printf "%v" .spec.table -}}{{- end -}}
{{- $priority := "" -}}
{{- if not (kindIs "invalid" .spec.priority) -}}{{- $priority = printf "%v" .spec.priority -}}{{- end -}}
{{- $entry := dict "dst" .spec.dst "gateway" $gateway "family" $family "table" $table "priority" $priority -}}
{{- $routes = append $routes $entry -}}
{{- end -}}
{{- end -}}
{{- toJson $routes -}}
{{- end -}}

{{- /* Scalar MAC address for the given link, or empty if the link is
       missing or has no hardwareAddr (virtual links have spec but may
       lack the field; test mocks may return {} for unknown ids). The
       field guard prevents `nil | toString` from rendering "<nil>". */ -}}
{{- define "talm.discovered.mac_by_link" -}}
{{- $link := lookup "links" "" . -}}
{{- if and $link $link.spec $link.spec.hardwareAddr -}}
{{- $link.spec.hardwareAddr | toString -}}
{{- end -}}
{{- end -}}

{{- /* Scalar PCI / bus path for the given link, or empty if the link is
       missing or has no busPath (virtual links such as bonds expose a
       spec without a busPath). The field guard prevents
       `nil | toString` from rendering "<nil>". */ -}}
{{- define "talm.discovered.bus_by_link" -}}
{{- $link := lookup "links" "" . -}}
{{- if and $link $link.spec $link.spec.busPath -}}
{{- $link.spec.busPath | toString -}}
{{- end -}}
{{- end -}}

{{- /* YAML fragment `busPath: <path>` for use as a Talos deviceSelector by
       link name. Prefer this over emitting `interface:` when you need the
       config to be portable across renames (e.g. predictable network names). */ -}}
{{- define "talm.discovered.link_selector_by_name" -}}
{{- $link := lookup "links" "" . -}}
{{- if and $link $link.spec.busPath -}}
busPath: {{ $link.spec.busPath }}
{{- end -}}
{{- end -}}

{{- /* Validate that a value is a well-formed DNS-1123 subdomain
       (RFC 1035 syntax + RFC 1123 leading-digit relaxation). On
       success returns the value verbatim so callers can pipe it
       into `quote` or use it inline. On any violation fails the
       render with a precise message naming the field and the
       offending value.

       Mirrors what k8s.io/apimachinery/pkg/util/validation
       .IsDNS1123Subdomain enforces in Go-side flag validation
       (talm init --name) so chart-rendered values agree with
       values an operator passes through the CLI:

         1. non-empty
         2. total length <= 253 chars
         3. matches RFC 1123 subdomain regex (lowercase, only
            [a-z0-9-.], each label starts/ends with [a-z0-9],
            no double dots)

       Per-label length (63 chars) is NOT enforced — upstream
       IsDNS1123Subdomain does not enforce it either, and there
       is no Talos-side cluster-name length cap that aligns with
       a 63-char floor. Stay symmetric with Go-side validation.

       Coercion: .value is rendered through `printf "%v"` before
       length / regex checks so an unquoted numeric YAML scalar
       (e.g. `clusterName: 123`) becomes the string "123" instead
       of crashing the template at `len of type int`. The eq-""
       emptiness check also avoids treating numeric 0 as falsy.

       Usage:
           {{ include "talm.validate.dns1123subdomain"
              (dict "value" .Values.clusterName "field" "clusterName") }}
       */ -}}
{{- define "talm.validate.dns1123subdomain" -}}
{{- $field := .field -}}
{{- $value := printf "%v" .value -}}
{{- if eq $value "" -}}
{{- fail (printf "values.yaml: %s must be a non-empty DNS-1123 subdomain (must be lowercase, only [a-z0-9-.], start and end with [a-z0-9], max 253 chars)" $field) -}}
{{- end -}}
{{- if gt (len $value) 253 -}}
{{- fail (printf "values.yaml: %s=%q exceeds 253 characters (DNS-1123 subdomain length limit)" $field $value) -}}
{{- end -}}
{{- if not (regexMatch "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$" $value) -}}
{{- fail (printf "values.yaml: %s=%q is not a valid DNS-1123 subdomain (must be lowercase, only [a-z0-9-.], start and end with [a-z0-9])" $field $value) -}}
{{- end -}}
{{- $value -}}
{{- end -}}
