---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    {{- include "platform.labels" . | nindent 4 }}

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  {{- include "platform.fluxDefaults" . | nindent 2 }}
  url: https://cloudnative-pg.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  {{- include "platform.helmReleaseDefaults" . | nindent 2 }}
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.28.0
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: HelmRepository
        name: cloudnative-pg
        namespace: cnpg-system
  values:
    cluster:
      instances: 2
      monitoring:
        enabled: true
