load('ext://helm_resource', 'helm_repo', 'helm_resource')

def load_balancer():
    k8s_yaml('./stacks/load-balancer/namespace.yaml')

    helm_repo(
        'metallb',
        'https://metallb.github.io/metallb',
        resource_name='metallb-repo',
        labels=['load-balancer']
    )

    helm_resource(
        'metallb',
        'metallb/metallb',
        namespace='load-balancer',
        flags=['--values=./stacks/load-balancer/values-metallb.yaml'],
        resource_deps=['metallb-repo'],
        labels=['load-balancer'],
    )

    k8s_yaml('./stacks/load-balancer/address-pool.yaml')
    k8s_resource(
        new_name='metallb-advertisement',
        objects=['default-advertisement:l2advertisement'],
        resource_deps=['metallb'],
        labels=['load-balancer'],
    )

    k8s_resource(
        new_name='metallb-pool',
        objects=['default-pool:IPAddressPool'],
        resource_deps=['metallb'],
        labels=['load-balancer'],
    )
