load('ext://helm_resource', 'helm_repo', 'helm_resource')

def metrics():
    k8s_yaml('./stacks/metrics/namespace.yaml')

    helm_repo(
        'prometheus',
        'https://prometheus-community.github.io/helm-charts',
        resource_name='prometheus-repo',
        labels=['metrics']
    )

    helm_resource(
        'kube-prometheus-stack',
        'prometheus/kube-prometheus-stack',
        namespace='metrics',
        flags=['--values=./stacks/metrics/values-prometheus.yaml'],
        resource_deps=['prometheus-repo'],
        labels=['metrics'],
    )
