name: Publish OCI Image
on:
  push:
    branches:
      - main

permissions:
  packages: write # needed for ghcr.io access

jobs:
  publish:
    name: Publish Contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          experimental: true

      - name: Log in to the Container registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: false

      - name: build
        run: mise run build

      - name: publish
        run: |
          OCI_REPO=oci://ghcr.io/dislogical/autolab/manifest
          IMAGE=$OCI_REPO:$(git rev-parse --short HEAD)

          # Push the manifest to the repo
          flux push artifact $IMAGE -f rendered.yaml \
            --reproducible \
            --source=$(git config --get remote.origin.url) \
            --revision=$(git branch --show-current)@sha1:$(git rev-parse HEAD) \
            --annotations='org.opencontainers.image.licenses=MIT' \
            --annotations='org.opencontainers.image.source=https://github.com/dislogical/autolab'

          # Tag the manifest as latest
          flux tag artifact $IMAGE --tag latest
