name: On Commit CI
on:
  - push

jobs:
  tilt-ci:
    name: Tilt CI - ${{ matrix.runtime.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - name: Kind
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          experimental: true

      - name: Run Tilt CI
        run: mise run test
