#!/bin/bash

IMAGE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Image info
export ARCH=armhf
export RELEASE=${RELEASE:-bookworm} # Don't forget to update stage0/prerun.sh
export IMG_NAME="${IMG_NAME:-raspios-$RELEASE-$ARCH}"
export DEPLOY_COMPRESSION=none

# Only emit the lite image
export STAGE_LIST=${STAGE_LIST:-$IMAGE_DIR/pi-gen/stage[0-2]}

# Emit the images in this directory
export DEPLOY_DIR=${DEPLOY_DIR:-$IMAGE_DIR/deploy}

# Release info
export PI_GEN=autolab
export PI_GEN_REPO=https://github.com/ColdenCullen/autolab
export PI_GEN_RELEASE=Raspberry Pi autolab image

# Locale info
export LOCALE_DEFAULT=en_US.UTF-8
export KEYBOARD_KEYMAP=us
export KEYBOARD_LAYOUT="English (US)"
export TIMEZONE_DEFAULT="America/Los_Angeles"

# User info
export FIRST_USER_NAME=autolab

# Network info
export WPA_COUNTRY=US
export ENABLE_SSH=1
